### PR TITLE
Use thread join before verifying the invalidation in BufferedObservingPreconditionTest

### LINKED ISSUE #202: BufferedObservingPreconditionTest fails randomly
The following occurred multiple times during the test-java-snapshot workflow:

> Error:  Failures: 
> Error:    BufferedObservingPreconditionTest.test processing thread dying invalidates test$sdccc:133 
> Wanted but not invoked:
> testRunObserver.invalidateTestRun(
>     <any string>,
>     <any>
> );
> -> at com.draeger.medical.sdccc.util.TestRunObserver.invalidateTestRun(TestRunObserver.java:68)
> Actually, there were zero interactions with this mock.

### PR DESCRIPTION
**Pull request by ldeichmann**
Use thread join before verifying the invalidation in BufferedObservingPreconditionTest
This ensures we wait for the call instead of randomly failing.

Closes #202.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [X] Pull Request Assignee
  * [x] Reviewer
* Adherence to javadoc conventions
  * [X] Pull Request Assignee
  * [x] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [X] Pull Request Assignee
  * [x] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [X] Pull Request Assignee
  * [x] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [X] Pull Request Assignee
  * [x] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [X] Pull Request Assignee
  * [x] Reviewer

### CODE REVIEW

File: sdccc/src/test/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPreconditionTest.kt [hunk 1]
```diff
@@ -130,9 +132,20 @@ internal class BufferedObservingPreconditionTest {
...
+        exampleObserving
+            .processingThread
+            .join(TIME_TO_WAIT_FOR_CHANGE.inWholeMilliseconds)
+
+        verify(
+            testRunObserver,
+            times(1)
+        ).invalidateTestRun(anyString(), any())
 
         // passing more changes is still possible
```
Comment (maximilianpilz) [inline sdccc/src/test/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPreconditionTest.kt:144]: Actually wrong now and previously only sometimes correct.

It will not add anything and instead call clear and return.

File: sdccc/src/test/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPreconditionTest.kt [hunk 2]
```diff
@@ -115,8 +116,9 @@ internal class BufferedObservingPreconditionTest {
     @Test
     internal fun `test processing thread dying invalidates test`() {
         val testRunObserver = mock<TestRunObserver>()
+        whenever(testRunObserver.isInvalid).thenReturn(false)
```
Comment (maximilianpilz) [inline sdccc/src/test/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPreconditionTest.kt:119]: Please remove this line.

File: sdccc/src/main/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPrecondition.kt [hunk 3]
```diff
@@ -27,7 +27,9 @@ abstract class BufferedObservingPrecondition(
     // this is going to be a problem when the manipulation is very long-running,
     // as the queue will fill up (quite quickly with waveforms)
     private val updateQueue = LinkedBlockingQueue<MdibChange>()
-    private val processingThread: Thread
+
+    // internal visibility to allow unit tests to inspect the thread. do not use for anything else
```
Comment (maximilianpilz) [inline sdccc/src/main/java/com/draeger/medical/sdccc/manipulation/precondition/BufferedObservingPrecondition.kt:31]: I think accessing it for synchronization purposes is valid outside of unittests too.

**Review by maximilianpilz — CHANGES_REQUESTED** [review]
I tried to limit my review comments to the changes and things affected by the changes introduced here as much as possible.

There are potentially additional issues with the processingThread which I did not comment on here, because it is kind of out of the scope of this pull request.
For example potentially calling manipulations from several threads could cause issues with test logic as well as libraries or packages e.g. with javax.swing.

**Review by maximilianpilz — APPROVED** [review]
